# Generated by Django 2.2 on 2022-01-16 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'рабочее место',
                'verbose_name_plural': 'Рабочие места',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateTimeField(verbose_name='Дата начала')),
                ('datetime_to', models.DateTimeField(verbose_name='Дата окончания')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Job', verbose_name='Рабочее место')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
